### ISSUE TITLE
Keeping PHP implementation apart from the domain list

### ISSUE THREAD

**Issue by martenson** [nojacko/email-validator#4]
Consider adding my disposable domain repo (https://github.com/martenson/disposable-email-domains) as a git submodule so we can work together on one list that is domain agnostic and you can continue here on your PHP validator implementation without the hassle of keeping the list up to date.

**Comment by nojacko** [comment]
This is something I had started with https://github.com/nojacko/email-data-disposable but never got around to polishing the bugs. Your library's in that ;) 

I want to keep this library as simple as possible without dependancies. Also, using the file returning a php array helps if be fast (no parsing or db).

I think one of the following, rather than a sub-module:
- I should finish the other library and include whitelisting too. Include that as dev dependency in composer and have a script to copy it into the data folder. 
- Include your project as the dev dependency and have a similar script to parse it into the data folder.

Both would require occasional running of the update script and committing. Pretty trivial. 

This way the email-validator library stays dependency free. 

I'm also contemplating a 2.0:
- updated API;
- whitelist for disposable & MX (i.e. gmail.com) to prevent MX queries;
- comparing MX records with known disposables;

but I digress...
